### ISSUE TITLE
Uncaught TypeError: list_stoechiometry is None instead of []

### ISSUE THREAD

**Issue by bdelepine** [brsynth/RetroPathRL#2]
Hi @tduigou,

Got this uncaught exception while doing some tests:

```python
Traceback (most recent call last):
  File "../RetroPathRL/Tree.py", line 1584, in <module>
    __cli()
  File "../RetroPathRL/Tree.py", line 1456, in __cli
    pathway_scoring=args.pathway_scoring)
  File "/home/retropath/Documents/RetroPathRL/Tree.py", line 288, in __init__
    use_RAVE=use_RAVE)
  File "/home/retropath/Documents/RetroPathRL/MCTS_node.py", line 126, in __init__
    self.moves = self.state.GetMoves(top_x = self.expansion_width, chemical_score = chemical_score)
  File "/home/retropath/Documents/RetroPathRL/chemical_compounds_state.py", line 413, in GetMoves
    extension = extension)
  File "/home/retropath/Documents/RetroPathRL/compound.py", line 817, in obtain_applicable_transformation_with_move
    list_stoechiometry = list_stoechiometry)
  File "/home/retropath/Documents/RetroPathRL/compound.py", line 144, in _moves_from_rdmols
    assert len(list_of_moves) == len(list_stoechiometry)
TypeError: object of type 'NoneType' has no len()
````

By playing around with prints, I saw that `list_stoechiometry` was set to None for whatever reason instead of [] as it is obviously expected from the code. I am not sure how bad it is though.

Its seems that it was stored like that in the (MongoDB) database since the `list_stoechiometry` value is inherited from `_ask_DB()`... but I am not sure if having a value for `rdmols_from_DB` and not for `list_stoechiometry` is expected behavior [line 73 in `compound.py`](https://github.com/brsynth/RetroPathRL/blob/master/compound.py#L73).

Important: I installed the MongoDB cache from brsynth/rp3_cache depot, but I had to modify RetroPathRL's `config.py` to use the package as it is expecting a "rp3_cache" and the actual name is "rp3_**d**cache" (which is another issue).

My ugly fix is to correct the type in [`_moves_from_rdmols()` line 93](https://github.com/brsynth/RetroPathRL/blob/master/compound.py#L93):
```python
...
    if clean_up:
        list_stoechiometry= []
    elif list_stoechiometry is None:  # for whatever reason
        list_stoechiometry = []
...
````

HTH, ++

**Comment by tduigou** [comment]
Hi @bdelepine,
Thank you warmly for your detailed feedback. I'll have a look to fix issue.
Best,

**Comment by tduigou** [comment]
The issue should be solved on the `master` branch

**Comment by bdelepine** [comment]
Hi @tduigou,

I'm afraid we still have a problem. My logs are full of the following line:

```
20/01/2020 10:06:05 -- WARNING -- Error local variable 'list_stoechiometry' referenced before assignment when trying rule RR-02-XXX on compound XXX. Moving to next rule
```

I see three things wrong here:
* this should be a critical error, not a warning
* as a developer, I would have preferred to see a traceback in the log (maybe it is already the case with the option --debug?)
* well, 'list_stoechiometry' is referenced before assignment 😉 

I should have latest version of RP3 from the master (but I didn't recompute the rules or anything since last runs).

From what I understood, the exception is raised from [compound.py#L852](https://github.com/brsynth/RetroPathRL/blob/master/compound.py#L852) and the problem is that, indeed, 'list_stochiometry' is not referenced in the [compound.py#L803](https://github.com/brsynth/RetroPathRL/blob/master/compound.py#L803) block.

I seems that I fixed it locally with:
```python
list_stoechiometry = db_reply['list_stoechiometry']
``` 

HTH, ++

**Comment by tduigou** [comment]
Hi @bdelepine,
Thanks for the feedback. Now the issue should be fixed.
Best,
